spring:
  datasource:
    url: jdbc:h2:file:./db/fiap-test
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: 'drop-and-create'
            drop-source: 'script-then-metadata'
            drop-script-source: 'drop-tables.sql'
  h2:
    console:
      enabled: true